name: Publish to NuGet and Visual Studio Marketplace

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Src/FluentAssertionsToShouldlyAnalyzer.sln

      - name: Build solution projects
        run: |
          dotnet build Src/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer  --configuration Release --no-restore
          dotnet build Src/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer.CodeFixes  --configuration Release --no-restore
          dotnet build Src/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer.Test  --configuration Release --no-restore
          dotnet build Src/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer.Package  --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Src/FluentAssertionsToShouldlyAnalyzer.sln --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack Src/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer.Package/FluentAssertionsToShouldlyAnalyzer.Package.csproj --configuration Release --output ./artifacts

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://apiint.nugettest.org/v3/index.json

