name: Publish to NuGet and Visual Studio Marketplace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore FluentAssertionsToShouldlyAnalyzer.sln

      - name: Build solution
        run: dotnet build FluentAssertionsToShouldlyAnalyzer.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test FluentAssertionsToShouldlyAnalyzer.sln --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer/FluentAssertionsToShouldlyAnalyzer.csproj --configuration Release --output ./artifacts

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json

    #   - name: Install vsce
    #     run: npm install -g vsce

    #   - name: Package VSIX extension
    #     run: vsce package --out ./artifacts

    #   - name: Publish to Visual Studio Marketplace
    #     env:
    #       VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
    #     run: |
    #       vsce publish --pat $VS_MARKETPLACE_PAT
